name: Release Please

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  release-please:
    name: Release Please
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release-please.outputs.tag_name }}
      should-release: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - id: release-please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        with:
          release-type: node
          token: ${{ github.token }}

  publish:
    name: Publish
    needs: release-please
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ needs.release-please.outputs.should-release == 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Build the extension
        run: pnpm build
      - name: Package the extension into a zip artifact
        run: pnpm package

      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          tag_name: ${{ needs.release-please.outputs.tag }}
          files: build/chrome-mv3-prod.zip
